spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://localhost:5432/click?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: 35.184.106.163:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: product
      auto-offset-reset: earliest

jwt:
  secret: thisispublickeythisispublickeythisispublickeythisispublickey

kafka:
  product:
    name: friendship-topic